# Generated by Django 4.1.4 on 2022-12-27 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=200)),
                ('company_mail', models.EmailField(max_length=254)),
                ('documents', models.FileField(upload_to='')),
                ('company_GST', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField()),
                ('is_pending', models.BooleanField()),
                ('is_rejected', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
