# Generated by Django 4.1.4 on 2022-12-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recruiterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='documents',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
