# Generated by Django 4.1.5 on 2023-01-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_recruiterprofile_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
