# Generated by Django 4.1.5 on 2023-01-13 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0009_remove_jobapplication_job_id'),
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplied',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobapplication'),
        ),
        migrations.AlterField(
            model_name='uploadresume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
