# Generated by Django 4.1.5 on 2023-01-05 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_alter_recruiterprofile_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=500)),
                ('job_type', models.CharField(max_length=500)),
                ('num_of_employees', models.CharField(max_length=500)),
                ('job_summery', models.CharField(max_length=500)),
                ('responsibility', models.CharField(max_length=500)),
                ('qualifications', models.CharField(max_length=500)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('no_of_openings', models.IntegerField()),
                ('job_rule', models.CharField(max_length=500)),
                ('industry_type', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recruiterprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_exp', models.IntegerField()),
                ('education', models.CharField(max_length=500)),
                ('skill', models.CharField(choices=[('py', 'python'), ('jv', 'java'), ('js', 'java_script'), ('php', 'PHP'), ('rb', 'RUBY'), ('C', 'C')], max_length=20)),
                ('Jobapplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qualification', to='recruiter.jobapplication')),
            ],
        ),
    ]
