# Generated by Django 4.1.5 on 2023-01-05 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_jobapplication_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
