# Generated by Django 4.1.5 on 2023-01-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_alter_jobapplication_industry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.CharField(blank=True, choices=[('bachlors', 'bachlors'), ('masters', 'masters'), ('phd', 'phd')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skill',
            field=models.CharField(blank=True, choices=[('py', 'python'), ('jv', 'java'), ('js', 'java_script'), ('php', 'PHP'), ('rb', 'RUBY'), ('C', 'C')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='year_of_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
