# Generated by Django 4.1.5 on 2023-01-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_jobapplication_education_jobapplication_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='year_of_exp',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experiance',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('one_yesr', '1 year'), ('two_year', '2 year'), ('fresher', 'Fresher'), ('fivce_year', '5 year')], max_length=500, null=True),
        ),
    ]
