# Generated by Django 4.1.5 on 2023-01-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_recruiterprofile_documents_and_more'),
        ('recruiter', '0006_remove_jobapplication_year_of_exp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='company_name',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recruiterprofile'),
        ),
    ]
